export const state = {
    activeView: "dashboard",
    activeTab: "sources",
    activeTriageFilter: "all",
    talkersData: [],
    exportersData: [],
    devicesData: [],
    anomaliesData: [],
    riskDevicesData: [],
    trafficSeriesData: [],
    activeTrafficRange: "24h",
    selectedDeviceIP: null,
    selectedAnomalyId: null,
    policiesData: [],
    selectedPolicyId: null,
    notificationRulesData: [],
    selectedNotificationRuleId: null,
    notificationLogsData: [],
    auditLogsData: [],
    auditLogPage: 0,
    auditLogPageSize: 10,
    unsavedChanges: {
        access: false,
        network: false,
        collectors: false,
        storage: false,
        thresholds: false,
        policies: false,
        notifications: false,
        integrations: false,
        system: false
    },
    settingsData: null,
    firstRunCompleted: true,
    firewallTemplates: null,
    activeFwTab: "unifi"
};
