title: FlowGuard Lite
description: Experimental self-hosted NetFlow/IPFIX visibility and anomaly-detection tool.
url: https://miquelbar.github.io
baseurl: /flowguard-lite
theme: jekyll-theme-cayman

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

plugins:
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true

defaults:
  - scope:
      path: ""
    values:
      layout: default
